
/*SOLUÇÃO DO EXERCICIO*/

/*____________________________________________________________*/

CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT (10,2),
	UF CHAR (2),
	ANO INT (4)

);

/*____________________________________________________________*/


/*CONECTANDO AO BANCO*/

USE LIVRARIA;

STATUS;

/*PROJETANDO A TABELA*/

SHOW TABLES;

DESC;


/*INSERINDO OS REGISTROS*/
/*csv*/
INSERT INTO LIVROS VALUES('CAVALEIRO REAL','ANA CLAUDIA','F',465,'ATLAS',49.9,'RJ',2009);
INSERT INTO LIVROS VALUES('A certeza de conseguir mais rapidamente','Theo Pinto','F';441,'Almeida Pinto - EI',33.92,'SP',2014);

/*#1 TRAZER TODOS OS DADOS*/
SELECT * FROM LIVROS;

/*#2 TRAZER O NOME DO LIVRO E O NOME DA EDITORA*/
SELECT LIVRO, EDITORA
FROM LIVROS;


/*#3 TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO*/
SELECT LIVRO, UF
FROM LIVROS
WHERE SEXO = 'M';

/*#4 TRAZER O NOME DO LIVRO E O NUMERO DE PAGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO*/
SELECT LIVRO, PAGINAS
FROM LIVROS
WHERE SEXO ='F';

/*#5 TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/
SELECT VALOR, UF
FROM LIVROS
WHERE UF = 'SP';

/*#6 TRAZER OS DADOS DOS AUTORES DO SEXO FEMININO QUE TIVERAM LIVROS PUBLICADOS POR SP OU RJ*/
SELECT AUTOR,SEXO,LIVRO
FROM LIVROS
WHERE SEXO = 'F'
AND (UF = 'RJ' OR UF = 'SP');
